//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HockeyPlayerParams", Namespace="http://tempuri.org/")]
    public partial class HockeyPlayerParams : object
    {
        
        private string positionField;
        
        private System.DateTime birthdayFromField;
        
        private System.DateTime birthdayToField;
        
        private int weightFromField;
        
        private int weightToField;
        
        private int heightFromField;
        
        private int heightToField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime birthdayFrom
        {
            get
            {
                return this.birthdayFromField;
            }
            set
            {
                this.birthdayFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime birthdayTo
        {
            get
            {
                return this.birthdayToField;
            }
            set
            {
                this.birthdayToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int weightFrom
        {
            get
            {
                return this.weightFromField;
            }
            set
            {
                this.weightFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int weightTo
        {
            get
            {
                return this.weightToField;
            }
            set
            {
                this.weightToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int heightFrom
        {
            get
            {
                return this.heightFromField;
            }
            set
            {
                this.heightFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int heightTo
        {
            get
            {
                return this.heightToField;
            }
            set
            {
                this.heightToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HockeyPlayer", Namespace="http://tempuri.org/")]
    public partial class HockeyPlayer : object
    {
        
        private string playeridField;
        
        private int jerseyField;
        
        private string fnameField;
        
        private string snameField;
        
        private string positionField;
        
        private System.DateTime birthdayField;
        
        private int weightField;
        
        private int heightField;
        
        private string birthcityField;
        
        private string birthstateField;
        
        private byte[] photoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string playerid
        {
            get
            {
                return this.playeridField;
            }
            set
            {
                this.playeridField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int jersey
        {
            get
            {
                return this.jerseyField;
            }
            set
            {
                this.jerseyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fname
        {
            get
            {
                return this.fnameField;
            }
            set
            {
                this.fnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sname
        {
            get
            {
                return this.snameField;
            }
            set
            {
                this.snameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string birthcity
        {
            get
            {
                return this.birthcityField;
            }
            set
            {
                this.birthcityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string birthstate
        {
            get
            {
                return this.birthstateField;
            }
            set
            {
                this.birthstateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] photo
        {
            get
            {
                return this.photoField;
            }
            set
            {
                this.photoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.WebService1Soap")]
    public interface WebService1Soap
    {
        
        // CODEGEN: Создание контракта сообщения, так как имя элемента params из пространства имен http://tempuri.org/ не отмечено как обнуляемое.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateParams", ReplyAction="*")]
        MyService.CreateParamsResponse CreateParams(MyService.CreateParamsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateParams", ReplyAction="*")]
        System.Threading.Tasks.Task<MyService.CreateParamsResponse> CreateParamsAsync(MyService.CreateParamsRequest request);
        
        // CODEGEN: Создание контракта сообщения, так как имя элемента SelectPlayersResult из пространства имен http://tempuri.org/ не отмечено как обнуляемое.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectPlayers", ReplyAction="*")]
        MyService.SelectPlayersResponse SelectPlayers(MyService.SelectPlayersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectPlayers", ReplyAction="*")]
        System.Threading.Tasks.Task<MyService.SelectPlayersResponse> SelectPlayersAsync(MyService.SelectPlayersRequest request);
        
        // CODEGEN: Создание контракта сообщения, так как имя элемента ID из пространства имен http://tempuri.org/ не отмечено как обнуляемое.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Image", ReplyAction="*")]
        MyService.ImageResponse Image(MyService.ImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Image", ReplyAction="*")]
        System.Threading.Tasks.Task<MyService.ImageResponse> ImageAsync(MyService.ImageRequest request);
        
        // CODEGEN: Создание контракта сообщения, так как имя элемента ID из пространства имен http://tempuri.org/ не отмечено как обнуляемое.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        MyService.TestResponse Test(MyService.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<MyService.TestResponse> TestAsync(MyService.TestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateParamsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateParams", Namespace="http://tempuri.org/", Order=0)]
        public MyService.CreateParamsRequestBody Body;
        
        public CreateParamsRequest()
        {
        }
        
        public CreateParamsRequest(MyService.CreateParamsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateParamsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyService.HockeyPlayerParams @params;
        
        public CreateParamsRequestBody()
        {
        }
        
        public CreateParamsRequestBody(MyService.HockeyPlayerParams @params)
        {
            this.@params = @params;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateParamsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateParamsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyService.CreateParamsResponseBody Body;
        
        public CreateParamsResponse()
        {
        }
        
        public CreateParamsResponse(MyService.CreateParamsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CreateParamsResponseBody
    {
        
        public CreateParamsResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectPlayersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectPlayers", Namespace="http://tempuri.org/", Order=0)]
        public MyService.SelectPlayersRequestBody Body;
        
        public SelectPlayersRequest()
        {
        }
        
        public SelectPlayersRequest(MyService.SelectPlayersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SelectPlayersRequestBody
    {
        
        public SelectPlayersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectPlayersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectPlayersResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyService.SelectPlayersResponseBody Body;
        
        public SelectPlayersResponse()
        {
        }
        
        public SelectPlayersResponse(MyService.SelectPlayersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SelectPlayersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyService.HockeyPlayer[] SelectPlayersResult;
        
        public SelectPlayersResponseBody()
        {
        }
        
        public SelectPlayersResponseBody(MyService.HockeyPlayer[] SelectPlayersResult)
        {
            this.SelectPlayersResult = SelectPlayersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Image", Namespace="http://tempuri.org/", Order=0)]
        public MyService.ImageRequestBody Body;
        
        public ImageRequest()
        {
        }
        
        public ImageRequest(MyService.ImageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        public ImageRequestBody()
        {
        }
        
        public ImageRequestBody(string ID)
        {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyService.ImageResponseBody Body;
        
        public ImageResponse()
        {
        }
        
        public ImageResponse(MyService.ImageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ImageResult;
        
        public ImageResponseBody()
        {
        }
        
        public ImageResponseBody(byte[] ImageResult)
        {
            this.ImageResult = ImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public MyService.TestRequestBody Body;
        
        public TestRequest()
        {
        }
        
        public TestRequest(MyService.TestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID;
        
        public TestRequestBody()
        {
        }
        
        public TestRequestBody(string ID)
        {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyService.TestResponseBody Body;
        
        public TestResponse()
        {
        }
        
        public TestResponse(MyService.TestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int TestResult;
        
        public TestResponseBody()
        {
        }
        
        public TestResponseBody(int TestResult)
        {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebService1SoapChannel : MyService.WebService1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<MyService.WebService1Soap>, MyService.WebService1Soap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), WebService1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebService1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyService.CreateParamsResponse MyService.WebService1Soap.CreateParams(MyService.CreateParamsRequest request)
        {
            return base.Channel.CreateParams(request);
        }
        
        public void CreateParams(MyService.HockeyPlayerParams @params)
        {
            MyService.CreateParamsRequest inValue = new MyService.CreateParamsRequest();
            inValue.Body = new MyService.CreateParamsRequestBody();
            inValue.Body.@params = @params;
            MyService.CreateParamsResponse retVal = ((MyService.WebService1Soap)(this)).CreateParams(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyService.CreateParamsResponse> MyService.WebService1Soap.CreateParamsAsync(MyService.CreateParamsRequest request)
        {
            return base.Channel.CreateParamsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyService.CreateParamsResponse> CreateParamsAsync(MyService.HockeyPlayerParams @params)
        {
            MyService.CreateParamsRequest inValue = new MyService.CreateParamsRequest();
            inValue.Body = new MyService.CreateParamsRequestBody();
            inValue.Body.@params = @params;
            return ((MyService.WebService1Soap)(this)).CreateParamsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyService.SelectPlayersResponse MyService.WebService1Soap.SelectPlayers(MyService.SelectPlayersRequest request)
        {
            return base.Channel.SelectPlayers(request);
        }
        
        public MyService.HockeyPlayer[] SelectPlayers()
        {
            MyService.SelectPlayersRequest inValue = new MyService.SelectPlayersRequest();
            inValue.Body = new MyService.SelectPlayersRequestBody();
            MyService.SelectPlayersResponse retVal = ((MyService.WebService1Soap)(this)).SelectPlayers(inValue);
            return retVal.Body.SelectPlayersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyService.SelectPlayersResponse> MyService.WebService1Soap.SelectPlayersAsync(MyService.SelectPlayersRequest request)
        {
            return base.Channel.SelectPlayersAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyService.SelectPlayersResponse> SelectPlayersAsync()
        {
            MyService.SelectPlayersRequest inValue = new MyService.SelectPlayersRequest();
            inValue.Body = new MyService.SelectPlayersRequestBody();
            return ((MyService.WebService1Soap)(this)).SelectPlayersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyService.ImageResponse MyService.WebService1Soap.Image(MyService.ImageRequest request)
        {
            return base.Channel.Image(request);
        }
        
        public byte[] Image(string ID)
        {
            MyService.ImageRequest inValue = new MyService.ImageRequest();
            inValue.Body = new MyService.ImageRequestBody();
            inValue.Body.ID = ID;
            MyService.ImageResponse retVal = ((MyService.WebService1Soap)(this)).Image(inValue);
            return retVal.Body.ImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyService.ImageResponse> MyService.WebService1Soap.ImageAsync(MyService.ImageRequest request)
        {
            return base.Channel.ImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyService.ImageResponse> ImageAsync(string ID)
        {
            MyService.ImageRequest inValue = new MyService.ImageRequest();
            inValue.Body = new MyService.ImageRequestBody();
            inValue.Body.ID = ID;
            return ((MyService.WebService1Soap)(this)).ImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyService.TestResponse MyService.WebService1Soap.Test(MyService.TestRequest request)
        {
            return base.Channel.Test(request);
        }
        
        public int Test(string ID)
        {
            MyService.TestRequest inValue = new MyService.TestRequest();
            inValue.Body = new MyService.TestRequestBody();
            inValue.Body.ID = ID;
            MyService.TestResponse retVal = ((MyService.WebService1Soap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyService.TestResponse> MyService.WebService1Soap.TestAsync(MyService.TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyService.TestResponse> TestAsync(string ID)
        {
            MyService.TestRequest inValue = new MyService.TestRequest();
            inValue.Body = new MyService.TestRequestBody();
            inValue.Body.ID = ID;
            return ((MyService.WebService1Soap)(this)).TestAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = long.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = long.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44319/WebService1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebService1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44319/WebService1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebService1Soap,
            
            WebService1Soap12,
        }
    }
}
